/**
 * Cookie sanitization and merging utility for Next.js BFF proxy.
 *
 * Prevents cookie injection and session tampering by stripping client-supplied
 * sensitive session tokens (`sid`, `sid_admin`) and only forwarding server-authenticated
 * tokens generated by NextAuth sessions.
 */

/**
 * Strips untrusted session tokens (`sid`, `sid_admin`) from a raw Cookie header string.
 *
 * @param existing Raw incoming Cookie header value
 * @returns Cleaned Cookie header string without sensitive session tokens
 */
export function sanitizeCookie(existing: string | null | undefined): string {
  if (!existing) return "";
  return existing
    .split(";")
    .map((c) => c.trim())
    .filter((c) => {
      if (!c) return false;
      const eqIdx = c.indexOf("=");
      const name = (eqIdx === -1 ? c : c.slice(0, eqIdx)).trim().toLowerCase();
      return name !== "sid" && name !== "sid_admin";
    })
    .join("; ");
}

/**
 * Merges a trusted session cookie into existing cookies after stripping
 * any untrusted client-supplied session identifiers.
 *
 * @param existing Raw incoming Cookie header value
 * @param extra Trusted cookie pair to append (e.g. `sid=${session.sid}`)
 * @returns Combined, sanitized Cookie header string
 */
export function mergeCookie(existing: string | null | undefined, extra?: string | null): string {
  const sanitized = sanitizeCookie(existing);
  const extraTrimmed = extra?.trim();
  if (!extraTrimmed) return sanitized;
  return sanitized ? `${sanitized}; ${extraTrimmed}` : extraTrimmed;
}
